In [1]:
import os
import sys
from pathlib import Path
module_path = Path('.').absolute().parents[4]
if str(module_path) not in sys.path:
    sys.path.append(str(module_path))

from capstone.quant.infrastructure.generic_data_container import GenericDataRequest, GenericDataContainer, GenericDataFrameFlatFileDataSource

In [2]:
# GenericDataFrameFlatFileDataSource provides a way to load any dataframe like data from a flat csv file
# just as any other data type, this fits into the -- DataRequest, DataSource, DataContainer -- triparty structure

# first create a generic data request
data_request = GenericDataRequest()

# then create a GenericDataFrameFlatFileDataSource, with the source csv file's name specified in the constructor
file_name = "capstone/quant/test_data/source/index_returns.csv"
file_name = module_path.resolve().joinpath(file_name).absolute()
data_source = GenericDataFrameFlatFileDataSource(file_name=file_name)

# calling datasource's initialize function will return an GenericDataContainer object, which contains the retrieved data
data_container = data_source.initialize(data_request)

# calling the get_data() interface function will get back the actual dataframe
data = data_container.get_data()

In [3]:
data.head()

,date,SPX,SX5E,RTY,NDQ,NKY,HSCEI,AS51
0,2024-01-05,0.001826,-0.002347,-0.003364,0.001472,0.002678,-0.007479,-0.000671
1,2024-01-08,0.014115,0.004922,0.019406,0.021090,0.000000,-0.022501,-0.005011
2,2024-01-09,-0.001478,-0.004082,-0.010543,0.001732,0.011558,-0.005667,0.009257
3,2024-01-10,0.005666,0.000405,0.001131,0.006855,0.020097,-0.005235,-0.006923
4,2024-01-11,-0.000671,-0.005975,-0.007514,0.001658,0.017657,0.013512,0.005030